### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by cemo** [braedon/prometheus-es-exporter#19]
I would like to add pod level labels to exported series. Is there a way to accomplish this?

Thank you so much for sharing your work.

**Comment by braedon** [comment]
Hi @cemo, assuming you're meaning Kubernetes Pods, I set labels (you can do the same with annotations) on the pods themselves, and then covert them to labels on the series in the [Prometheus config](https://prometheus.io/docs/operating/configuration/#kubernetes_sd_config).

```
- job_name: 'kubernetes-pods'

  kubernetes_sd_configs:
  - role: pod

  relabel_configs:
  ...
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  ...
```

I started off with the [example config](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml) from the Prometheus repo, and customised from there.
