### ISSUE TITLE
Reload when config is updated

### ISSUE THREAD

**Issue by jackiepg12** [braedon/prometheus-es-exporter#46]
How to reload when the config is updated?

**Comment by braedon** [comment]
Hi @jackiepg12, there's (currently) no support for reloading the config on the fly - either automatically or via a signal. The config is only read on startup, so if you need to modify it, you'll need to restart the exporter.

If you'd like to work on a config reload feature, I'd be happy to discuss how it might work?

**Comment by jonny-wg2** [comment]
@jackiepg12 best way to reload the config is just redeploy the exporter or kill the pod. This is pretty common with many apps when it comes to initializing config at runtime.

**Comment by opsforce** [comment]
@jackiepg12 
if you use Kubernetes, maybe [stakater-reloader](https://github.com/stakater/Reloader) can help you.

**Comment by jonny-wg2** [comment]
+2 on `stakater-reloader` . we have this and it works great

**Comment by xuanyuanaosheng** [comment]
@opsforce @jonny-wg2  Could you  please give a example ?

**Comment by jonny-wg2** [comment]
The reloader docs will help.

But here you go
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-exporter
  namespace: monitoring
  annotations:
    configmap.reloader.stakater.com/reload: "es-exporter"
    flux.weave.works/automated: "true"
spec:
```
